apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-prod
  namespace: adn-team-1
  annotations:
    kargo.akuity.io/authorized-stage: team-1-podtato-kargo-project:prod
spec:
  destination:
    namespace: team-1-podtato-prod
    name: spoke-cluster-prod
  project: team-1-project
  source:
    repoURL: https://github.com/kubriX-demo/team-1-podtato-head
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: adn-team-1_podtato-prod:app/Namespace:team-1-podtato-prod/team-1-podtato-prod
    syncOptions:
    - CreateNamespace=true

